# Use an official lightweight Python image
FROM python:3.10

# Set the working directory in the container
WORKDIR /

COPY . .

RUN pip install --upgrade pip && pip install -r requirements.txt

# Set the default command to run the training script
CMD ["python", "MLFlow/train.py"]
